// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "pkg.formatio/prisma/db"

	types "pkg.formatio/types"
)

// MockISocialConnectionDao is an autogenerated mock type for the ISocialConnectionDao type
type MockISocialConnectionDao struct {
	mock.Mock
}

// CreateConnection provides a mock function with given fields: _a0
func (_m *MockISocialConnectionDao) CreateConnection(_a0 types.CreateConnectionArgs) (*db.SocialConnectionModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnection")
	}

	var r0 *db.SocialConnectionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.CreateConnectionArgs) (*db.SocialConnectionModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.CreateConnectionArgs) *db.SocialConnectionModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SocialConnectionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.CreateConnectionArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConnection provides a mock function with given fields: _a0
func (_m *MockISocialConnectionDao) DeleteConnection(_a0 types.DeleteConnectionArgs) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.DeleteConnectionArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConnection provides a mock function with given fields: _a0
func (_m *MockISocialConnectionDao) GetConnection(_a0 types.GetConnectionArgs) (*db.SocialConnectionModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetConnection")
	}

	var r0 *db.SocialConnectionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.GetConnectionArgs) (*db.SocialConnectionModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.GetConnectionArgs) *db.SocialConnectionModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SocialConnectionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.GetConnectionArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConnections provides a mock function with given fields: _a0
func (_m *MockISocialConnectionDao) ListConnections(_a0 types.ListConnectionsArgs) ([]db.SocialConnectionModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListConnections")
	}

	var r0 []db.SocialConnectionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.ListConnectionsArgs) ([]db.SocialConnectionModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.ListConnectionsArgs) []db.SocialConnectionModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.SocialConnectionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.ListConnectionsArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConnection provides a mock function with given fields: _a0
func (_m *MockISocialConnectionDao) UpdateConnection(_a0 types.UpdateConnectionArgs) (*db.SocialConnectionModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnection")
	}

	var r0 *db.SocialConnectionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.UpdateConnectionArgs) (*db.SocialConnectionModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.UpdateConnectionArgs) *db.SocialConnectionModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SocialConnectionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.UpdateConnectionArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockISocialConnectionDao creates a new instance of MockISocialConnectionDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISocialConnectionDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISocialConnectionDao {
	mock := &MockISocialConnectionDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
