quiet: False
keeptree: False
disable-version-string: True
with-expecter: False
mockname: "Mock{{.InterfaceName}}"
all: True
packages:
  github.com/struckchure/idp/dao:
    config:
      recursive: True
      dir: "mocks/{{.PackageName}}"
      outpkg: mocks
      inpackage: False
  github.com/struckchure/idp/services:
    config:
      recursive: True
      dir: "mocks/{{.PackageName}}"
      outpkg: mocks
      inpackage: False
  github.com/struckchure/idp/internals:
    config:
      recursive: True
      dir: "mocks/{{.PackageName}}"
      outpkg: mocks
      inpackage: False
