// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	lib "pkg.formatio/lib"
)

// MockScheduleOption is an autogenerated mock type for the ScheduleOption type
type MockScheduleOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockScheduleOption) Execute(_a0 *lib.ScheduleArgs) {
	_m.Called(_a0)
}

// NewMockScheduleOption creates a new instance of MockScheduleOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleOption {
	mock := &MockScheduleOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
