// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	db "pkg.formatio/prisma/db"

	types "pkg.formatio/types"
)

// MockIMachineService is an autogenerated mock type for the IMachineService type
type MockIMachineService struct {
	mock.Mock
}

// CreateMachine provides a mock function with given fields: _a0
func (_m *MockIMachineService) CreateMachine(_a0 types.CreateMachineArgs) (*db.MachineModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateMachine")
	}

	var r0 *db.MachineModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.CreateMachineArgs) (*db.MachineModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.CreateMachineArgs) *db.MachineModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.MachineModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.CreateMachineArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateMachineEventHandler provides a mock function with given fields: _a0
func (_m *MockIMachineService) CreateMachineEventHandler(_a0 types.CreateMachineEventHandlerArgs) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateMachineEventHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.CreateMachineEventHandlerArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMachine provides a mock function with given fields: _a0
func (_m *MockIMachineService) DeleteMachine(_a0 types.DeleteMachineArgs) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMachine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.DeleteMachineArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMachineEventHandler provides a mock function with given fields: _a0
func (_m *MockIMachineService) DeleteMachineEventHandler(_a0 types.DeleteMachineEventHandlerArgs) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMachineEventHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.DeleteMachineEventHandlerArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMachine provides a mock function with given fields: _a0
func (_m *MockIMachineService) GetMachine(_a0 types.GetMachineArgs) (*db.MachineModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetMachine")
	}

	var r0 *db.MachineModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.GetMachineArgs) (*db.MachineModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.GetMachineArgs) *db.MachineModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.MachineModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.GetMachineArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMachines provides a mock function with given fields: _a0
func (_m *MockIMachineService) ListMachines(_a0 types.ListMachineArgs) ([]db.MachineModel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListMachines")
	}

	var r0 []db.MachineModel
	var r1 error
	if rf, ok := ret.Get(0).(func(types.ListMachineArgs) ([]db.MachineModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.ListMachineArgs) []db.MachineModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.MachineModel)
		}
	}

	if rf, ok := ret.Get(1).(func(types.ListMachineArgs) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMachine provides a mock function with given fields: _a0
func (_m *MockIMachineService) UpdateMachine(_a0 types.UpdateMachineArgs) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMachine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UpdateMachineArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMachineEventHandler provides a mock function with given fields: _a0
func (_m *MockIMachineService) UpdateMachineEventHandler(_a0 types.UpdateMachineArgs) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMachineEventHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.UpdateMachineArgs) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockIMachineService creates a new instance of MockIMachineService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMachineService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMachineService {
	mock := &MockIMachineService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
