// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRemoveFieldOption is an autogenerated mock type for the RemoveFieldOption type
type MockRemoveFieldOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockRemoveFieldOption) Execute(_a0 map[string]interface{}) {
	_m.Called(_a0)
}

// NewMockRemoveFieldOption creates a new instance of MockRemoveFieldOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemoveFieldOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemoveFieldOption {
	mock := &MockRemoveFieldOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
