package config

import (
	"pkg.formatio/lib"
)

func NewEnv() lib.Env {
	return lib.Env{
		DB_SSL_MODE:    "disable",
		DB_CLIENT_CERT: "DB_CLIENT_CERT",

		PG_HOST:     "localhost",
		PG_USER:     "test_user",
		PG_PASSWORD: "test_password",
		PG_DB:       "test_db",
		PG_PORT:     "5432",

		APP_PORT:    "3000",
		SOCKET_PORT: "9090",

		JWT_ACCESS_KEY:  "JWT_ACCESS_KEY",
		JWT_REFRESH_KEY: "JWT_REFRESH_KEY",

		GH_APP_SLUG:          "GH_APP_SLUG",
		GH_APP_ID:            "GH_APP_ID",
		GH_APP_CLIENT_ID:     "GH_APP_CLIENT_ID",
		GH_APP_CLIENT_SECRET: "GH_APP_CLIENT_SECRET",
		GH_PRIVATE_KEY:       "GH_PRIVATE_KEY",

		DEFAULT_ADMIN_EMAIL: "DEFAULT_ADMIN_EMAIL",
		DEFAULT_ADMIN_PASS:  "DEFAULT_ADMIN_PASS",

		AUTH0_DOMAIN:    "AUTH0_DOMAIN",
		AUTH0_CLIENT_ID: "AUTH0_CLIENT_ID",

		RABBITMQ_URL: "RABBITMQ_URL",

		K8S_CLUSTER_CONFIG: "K8S_CLUSTER_CONFIG",

		INGRESS_ROOT_DOMAIN: "INGRESS_ROOT_DOMAIN",

		REDIS_URL: "REDIS_URL",
	}
}
