name: Basic App Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  - name: build
    runs-on: self-hosted
    steps:
      - name: Build App
        run: echo "build app 2 ..."

  - name: deploy
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy App
        run: echo "deploying app 2 ..."
