name: Basic App Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  - name: build
    runs-on: self-hosted
    steps:
      - name: Build App
        run: echo "build app ..."

  - name: test
    runs-on: self-hosted
    needs: build
    steps:
      - name: Test App
        run: echo "testing app ..."

  - name: deploy
    runs-on: self-hosted
    needs: test
    steps:
      - name: Deploy App
        run: echo "deploying app ..."

  - name: release
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Release App
        run: echo "releasing app ..."
