// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "idp Team",
            "email": "idp@overal-x.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "operationId": "loginUser",
                "parameters": [
                    {
                        "description": "Login User",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.LoginUserArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.LoginUserResult"
                        }
                    }
                }
            }
        },
        "/auth/refresh-access-token/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "operationId": "refreshAccessToken",
                "parameters": [
                    {
                        "description": "Refresh Access Token",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RefreshAccessTokenArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.LoginUserResult"
                        }
                    }
                }
            }
        },
        "/auth/register/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "operationId": "registerUser",
                "parameters": [
                    {
                        "description": "Register User",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RegisterUserArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.RegisterUserResult"
                        }
                    }
                }
            }
        },
        "/deployments": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "operationId": "listDeployments",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine Id",
                        "name": "machineId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "machineId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "repoConnectionId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sortBy",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "take",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.DeploymentModel"
                            }
                        }
                    }
                }
            }
        },
        "/deployments/deploy": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "operationId": "deployRepo",
                "parameters": [
                    {
                        "description": "Deploy Repo",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.DeployRepoArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/deployments/{deploymentId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "operationId": "getDeploymentById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment Id",
                        "name": "deploymentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.DeploymentModel"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentId}/logs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployments"
                ],
                "operationId": "listDeploymentLogsById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment Id",
                        "name": "deploymentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.DeploymentLogModel"
                            }
                        }
                    }
                }
            }
        },
        "/gh/account-connections": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "operationId": "listAccountConnections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.GithubAccountConnectionModel"
                            }
                        }
                    }
                }
            }
        },
        "/gh/authorize": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "operationId": "authorizeGithubAccount",
                "parameters": [
                    {
                        "type": "string",
                        "name": "redirectUrl",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RedirectResult"
                        }
                    }
                }
            }
        },
        "/gh/repos": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "operationId": "ListRepositories",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "name": "pageNumber",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Repository"
                            }
                        }
                    }
                }
            }
        },
        "/gh/update-app-access": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "operationId": "updateAppAccess",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RedirectResult"
                        }
                    }
                }
            }
        },
        "/machine": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "machines"
                ],
                "operationId": "listMachines",
                "parameters": [
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sortBy",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "take",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.MachineModel"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "machines"
                ],
                "operationId": "createMachine",
                "parameters": [
                    {
                        "description": "List Machine",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateMachineArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db.MachineModel"
                        }
                    }
                }
            }
        },
        "/machine/{machineId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "machines"
                ],
                "operationId": "getMachine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine Id",
                        "name": "machineId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.MachineModel"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "machines"
                ],
                "operationId": "deleteMachine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine Id",
                        "name": "machineId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "machines"
                ],
                "operationId": "updateMachine",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine Id",
                        "name": "machineId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Machine",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateMachineArgs"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/network": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "operationId": "listNetworks",
                "parameters": [
                    {
                        "type": "string",
                        "name": "machineId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sortBy",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "take",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.NetworkModel"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "operationId": "createNetwork",
                "parameters": [
                    {
                        "description": "List Networks",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateNetworkArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db.NetworkModel"
                        }
                    }
                }
            }
        },
        "/network/{networkId}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "network"
                ],
                "operationId": "deleteNetwork",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Network Id",
                        "name": "networkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/repo-connection": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-connection"
                ],
                "operationId": "listRepoConnections",
                "parameters": [
                    {
                        "type": "string",
                        "name": "machineId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "sortBy",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "take",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.RepoConnectionModel"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-connection"
                ],
                "operationId": "createRepoConnection",
                "parameters": [
                    {
                        "description": "Create Repo Connection",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateRepoConnectionArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/db.RepoConnectionModel"
                        }
                    }
                }
            }
        },
        "/repo-connection/{connectionId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-connection"
                ],
                "operationId": "getRepoConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repo Connection Id",
                        "name": "connectionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/db.RepoConnectionModel"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-connection"
                ],
                "operationId": "deleteRepoConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repo Connection Id",
                        "name": "connectionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo-connection"
                ],
                "operationId": "updateRepoConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repo Connection Id",
                        "name": "connectionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Repo Connection",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateRepoConnectionArgs"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/db.RepoConnectionModel"
                        }
                    }
                }
            }
        },
        "/user/profile/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "getProfileUser",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/db.UserModel"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "operationId": "updateProfileUser",
                "parameters": [
                    {
                        "description": "Update User",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateUserArgs"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/db.UserModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.DeploymentLogModel": {
            "type": "object",
            "required": [
                "createdAt",
                "deploymentId",
                "id",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "deployment": {
                    "$ref": "#/definitions/db.DeploymentModel"
                },
                "deploymentId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jobId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "db.DeploymentModel": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "machineId",
                "repoConnectionId",
                "status",
                "updatedAt"
            ],
            "properties": {
                "DeploymentLog": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.DeploymentLogModel"
                    }
                },
                "actor": {
                    "type": "string"
                },
                "commitHash": {
                    "type": "string"
                },
                "commitMessage": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "machine": {
                    "$ref": "#/definitions/db.MachineModel"
                },
                "machineId": {
                    "type": "string"
                },
                "repoConnection": {
                    "$ref": "#/definitions/db.RepoConnectionModel"
                },
                "repoConnectionId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/db.DeploymentStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "db.DeploymentStatus": {
            "type": "string",
            "enum": [
                "IDLE",
                "IN_PROGRESS",
                "SUCCESSFUL",
                "FAILED"
            ],
            "x-enum-varnames": [
                "DeploymentStatusIdle",
                "DeploymentStatusInProgress",
                "DeploymentStatusSuccessful",
                "DeploymentStatusFailed"
            ]
        },
        "db.GithubAccountConnectionModel": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "updatedAt",
                "userId"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "githubEmail": {
                    "type": "string"
                },
                "githubId": {
                    "type": "string"
                },
                "githubInstallationId": {
                    "type": "integer"
                },
                "githubUsername": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/db.UserModel"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "db.MachineModel": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "machineStatus",
                "ownerId",
                "updatedAt"
            ],
            "properties": {
                "Deployment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.DeploymentModel"
                    }
                },
                "Network": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.NetworkModel"
                    }
                },
                "RepoConnection": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.RepoConnectionModel"
                    }
                },
                "containerId": {
                    "type": "string"
                },
                "cpu": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "machineImage": {
                    "type": "string"
                },
                "machineName": {
                    "type": "string"
                },
                "machineStatus": {
                    "$ref": "#/definitions/db.MachineStatus"
                },
                "memory": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/db.UserModel"
                },
                "ownerId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "db.MachineStatus": {
            "type": "string",
            "enum": [
                "CREATING",
                "RUNNING",
                "REBOOTING",
                "SHUTTING_DOWN",
                "SHUTDOWN"
            ],
            "x-enum-varnames": [
                "MachineStatusCreating",
                "MachineStatusRunning",
                "MachineStatusRebooting",
                "MachineStatusShuttingDown",
                "MachineStatusShutdown"
            ]
        },
        "db.NetworkModel": {
            "type": "object",
            "required": [
                "createdAt",
                "destinationPort",
                "id",
                "listeningPort",
                "machineId",
                "updatedAt"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "destinationPort": {
                    "type": "integer"
                },
                "hostName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ingressId": {
                    "type": "string"
                },
                "listeningPort": {
                    "type": "integer"
                },
                "machine": {
                    "$ref": "#/definitions/db.MachineModel"
                },
                "machineId": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "serviceId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "db.RepoConnectionModel": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "machineId",
                "updatedAt"
            ],
            "properties": {
                "Deployment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.DeploymentModel"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "machine": {
                    "$ref": "#/definitions/db.MachineModel"
                },
                "machineId": {
                    "type": "string"
                },
                "repoId": {
                    "type": "string"
                },
                "repoName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "db.UserModel": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "roles",
                "updatedAt"
            ],
            "properties": {
                "GithubAccountConnection": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.GithubAccountConnectionModel"
                    }
                },
                "Machine": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.MachineModel"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "handlers.RedirectResult": {
            "type": "object",
            "required": [
                "link"
            ],
            "properties": {
                "link": {
                    "type": "string"
                }
            }
        },
        "internals.AuthTokens": {
            "type": "object",
            "required": [
                "accessToken",
                "refreshToken"
            ],
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "services.DeployRepoArgs": {
            "type": "object",
            "required": [
                "connectionId",
                "ref"
            ],
            "properties": {
                "connectionId": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                }
            }
        },
        "types.CreateMachineArgs": {
            "type": "object",
            "required": [
                "cpu",
                "machineImage",
                "machineName",
                "memory"
            ],
            "properties": {
                "cpu": {
                    "type": "string"
                },
                "machineImage": {
                    "type": "string"
                },
                "machineName": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                }
            }
        },
        "types.CreateNetworkArgs": {
            "type": "object",
            "required": [
                "destinationPort",
                "listeningPort",
                "machineId",
                "protocol"
            ],
            "properties": {
                "destinationPort": {
                    "type": "integer"
                },
                "listeningPort": {
                    "type": "integer"
                },
                "machineId": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "types.CreateRepoConnectionArgs": {
            "type": "object",
            "required": [
                "machineId",
                "repoId",
                "repoName"
            ],
            "properties": {
                "machineId": {
                    "type": "string"
                },
                "repoId": {
                    "type": "string"
                },
                "repoName": {
                    "type": "string"
                }
            }
        },
        "types.LoginUserArgs": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "types.LoginUserResult": {
            "type": "object",
            "required": [
                "tokens"
            ],
            "properties": {
                "tokens": {
                    "$ref": "#/definitions/internals.AuthTokens"
                }
            }
        },
        "types.RefreshAccessTokenArgs": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "types.RegisterUserArgs": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "types.RegisterUserResult": {
            "type": "object",
            "required": [
                "createdAt",
                "id",
                "roles",
                "tokens",
                "updatedAt"
            ],
            "properties": {
                "GithubAccountConnection": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.GithubAccountConnectionModel"
                    }
                },
                "Machine": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.MachineModel"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tokens": {
                    "$ref": "#/definitions/internals.AuthTokens"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "types.Repository": {
            "type": "object",
            "required": [
                "fullName",
                "id",
                "name",
                "private",
                "url"
            ],
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "types.UpdateMachineArgs": {
            "type": "object",
            "required": [
                "cpu",
                "machineImage",
                "machineName",
                "memory",
                "ownerId"
            ],
            "properties": {
                "cpu": {
                    "type": "string"
                },
                "machineImage": {
                    "type": "string"
                },
                "machineName": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                }
            }
        },
        "types.UpdateRepoConnectionArgs": {
            "type": "object",
            "required": [
                "machineId",
                "repoId",
                "repoName"
            ],
            "properties": {
                "machineId": {
                    "type": "string"
                },
                "repoId": {
                    "type": "string"
                },
                "repoName": {
                    "type": "string"
                }
            }
        },
        "types.UpdateUserArgs": {
            "type": "object",
            "required": [
                "firstName",
                "lastName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "idp API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
